___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

**NumPy (or Numpy)** is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np #istallation of numpy
print(np.__version__)  #print numpy version and the configuration

1.13.3


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

**NumPy arrays** are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [97]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.arange(10,51,2) #an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(10,50)[::-1] #reverse vector (first element becomes last)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
table = np.zeros(10) #a null vector of size 10 but the fifth value which is 1
table[4]=1
table

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.ones(3)

array([ 1.,  1.,  1.])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
np.ones(10)*5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

### linspace
Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,3) #an array of 3 linearly spaced points between 0 and 10

array([  0.,   5.,  10.])

In [18]:
np.linspace(0,10,50) #an array of 50 linearly spaced points between 0 and 10

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [19]:
np.linspace (0,1,20) #an array of 20 linearly spaced points between 0 and 1

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## eye

Creates an identity matrix

In [20]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [21]:
np.random.rand(1) #a random number between 0 and 1

array([ 0.32301481])

In [22]:
np.random.rand(2)

array([ 0.35767122,  0.6675572 ])

In [23]:
np.random.rand(5,5)

array([[ 0.5142099 ,  0.79033957,  0.13567129,  0.23044982,  0.74676548],
       [ 0.00835479,  0.68733429,  0.6974004 ,  0.25778124,  0.37610594],
       [ 0.52713214,  0.31270908,  0.35384232,  0.51672822,  0.27387784],
       [ 0.33290921,  0.4643524 ,  0.44561002,  0.01139955,  0.55675232],
       [ 0.24430143,  0.41442345,  0.76889487,  0.5654906 ,  0.10067893]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(2)

array([-1.5310745 ,  0.25205075])

In [25]:
np.random.randn(5,5)

array([[ 1.33231413, -0.63062685, -0.31306535, -0.87854262, -1.07165912],
       [-1.98755075, -0.53306139,  1.25812222,  1.48968159,  0.99246528],
       [-0.97200179,  0.05734204, -0.84846962,  0.26683788,  0.5457428 ],
       [-0.27362772, -0.13688722,  1.03869188, -0.29674538, -1.31579721],
       [ 0.49769374, -1.05769982,  0.615112  ,  1.21262784,  1.02319605]])

In [26]:
np.random.randn(25) #an array of 25 random numbers sampled from a standard normal distribution

array([-1.95756939, -0.58297495, -0.53611169,  0.60775884, -1.04912243,
       -0.79507547, -0.14672324,  0.13727889, -0.1291544 , -0.70944443,
        0.69642266, -1.7530701 ,  0.52466128,  0.33049639,  0.47961182,
       -0.29857813,  0.81738276, -0.51802431,  1.06423782,  0.49111527,
       -1.6536841 ,  0.70342998, -0.88503906,  1.14103433,  2.0365812 ])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,100)

63

In [28]:
np.random.randint(1,100,10)

array([90, 62, 96, 95, 31, 87,  6, 97, 14, 76])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([ 5, 48, 46, 47, 37, 36, 40, 21, 37, 35])

## Reshape
Returns an array containing the same data with a new shape.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
np.arange(9).reshape(3,3) # a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.arange(1,101).reshape(10,10)/100

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [35]:
np.arange(1,101).reshape(10,10)/100.0

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

### max,min,argmax,argmin, sum, std ,...

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [36]:
arr = np.random.randint(0,50,10)
arr

array([44, 20, 12, 19,  6, 48, 35, 41,  4, 46])

In [37]:
arr.argmax() #show index locations of max values

5

In [38]:
arr.min()

4

In [39]:
arr.argmin() #show index locations of min values

8

In [40]:
arr_1 = np.arange(1,26).reshape(5,5)
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr_1.sum() #summ of all the values in array arr_1

325

In [42]:
arr_1.std() # standard deviation of the values in array arr_1

7.2111025509279782

In [43]:
arr_1.sum(axis=0) #sum of all the columns in array arr_1

array([55, 60, 65, 70, 75])

In [44]:
arr_1.sum() #sum of all the rows in array arr_1

325

In [45]:
#Taking Square Roots
np.sqrt(arr_1)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798],
       [ 2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766],
       [ 3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335],
       [ 4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595],
       [ 4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ]])

In [46]:
#Calcualting exponential (e^)
np.exp(arr_1)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
          8.10308393e+03,   2.20264658e+04],
       [  5.98741417e+04,   1.62754791e+05,   4.42413392e+05,
          1.20260428e+06,   3.26901737e+06],
       [  8.88611052e+06,   2.41549528e+07,   6.56599691e+07,
          1.78482301e+08,   4.85165195e+08],
       [  1.31881573e+09,   3.58491285e+09,   9.74480345e+09,
          2.64891221e+10,   7.20048993e+10]])

In [47]:
np.max(arr_1) #same as arr_1.max()

25

In [48]:
np.sin(np.linspace(0,2*np.pi,100))

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [49]:
np.log(arr_1)

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509],
       [ 2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ],
       [ 2.77258872,  2.83321334,  2.89037176,  2.94443898,  2.99573227],
       [ 3.04452244,  3.09104245,  3.13549422,  3.17805383,  3.21887582]])

## Shape

Shape is an attribute that arrays have (not a method):

In [50]:
arr = np.arange(25) # this is vector
arr.shape


(25L,)

In [51]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
arr.reshape(1,25).shape

(1L, 25L)

In [53]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(25,1).shape

(25L, 1L)

### dtype

You can also grab the data type of the object in the array:

In [55]:
arr.dtype

dtype('int32')

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [56]:
import numpy as np
arr = np.arange(0,10)

In [57]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\Tomek\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [61]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\Tomek\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in divide
  


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

# NumPy Indexing and Selection

In [63]:
arr_2 = np.arange(0,11)
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [64]:
#Get a value at an index
arr_2[8]

8

In [65]:
#Get values in a range
arr_2[1:5]

array([1, 2, 3, 4])

In [66]:
#Get values in a range
arr_2[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [67]:
#Setting a value with index range (Broadcasting)
arr_2[0:5]=100

#Show
arr_2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
# Reset array, we'll see why I had to reset in  a moment
arr_2 = np.arange(0,11)

#Show
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
#Important notes on Slices
slice_of_arr_2 = arr_2[0:6]

#Show slice
slice_of_arr_2

array([0, 1, 2, 3, 4, 5])

In [70]:
#Change Slice
slice_of_arr_2[:]=99

#Show Slice again
slice_of_arr_2

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [71]:
#To get a copy, need to be explicit
arr_2_copy = arr.copy()

arr_2_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [72]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [74]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [75]:
# Getting individual element value
arr_2d[1,0]

20

In [76]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [78]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [79]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [81]:
mat[3,4]

20

In [82]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [83]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [84]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [85]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [86]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10L

In [87]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [88]:
#Fancy indexing allows the following
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [89]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [90]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [92]:
bool_arr = arr>4

In [93]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [94]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])